### ISSUE TITLE
Angular.easy-pie-chart not being used

### ISSUE THREAD

**Issue by shooftie** [rendro/easy-pie-chart#108]
I have a project in which I am trying to use the angular directives of easy-pie-chart.

I have installed the bower component and it is being listed in my bower.json.

I am using Gulp which I believe means that I do not need RequireJS.

The problem seems to be that:
1. No matter what I do, jquery.easy-pie-chart is being used rather than angular.easy-pie-chart
2. The only way that I can prevent RequireJS from being included is to exclude it in my gulp.js

If I hack it [manually copy angular.easy-pie-chart.js from to dist to libs and replace links to  jquery.easy-pie-chart,js and require.js with a single inclusion for angular.easy-pie-chart.js] it all works as expected.

Suspect probably an issue with me...

**Comment by enkodellc** [comment]
You should be using Gulp overrides. https://www.npmjs.com/package/gulp-bower-overrides

```
  "overrides": {
    "jquery.easy-pie-chart": {
      "main": [
        "dist/angular.easypiechart.js"
      ]
    }
}
```
