### ISSUE TITLE
Multiple  Value

### ISSUE THREAD

**Issue by arvindstutzen** [rendro/easy-pie-chart#118]
Is it possible to have multiple value in piechart with each bar has different colour.

**Comment by vankooch** [comment]
Is it?

**Comment by rendro** [comment]
no. it is not. Keep an eye on branch v3.0

**Comment by jangix** [comment]
https://github.com/rendro/easy-pie-chart/issues/203

**Comment by jangix** [comment]
vedere qui https://github.com/rendro/easy-pie-chart/issues/203

**Comment by jangix** [comment]
read here https://github.com/rendro/easy-pie-chart/issues/203
