### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by stevelacy** [rendro/easy-pie-chart#124]
Would you be interested in publishing this to npm to support Browserify, webpack, and other npm client loaders since it has a vanillajs instance?

**Comment by mrzmyr** [comment]
+1, @rendro what do you think ?

**Comment by rendro** [comment]
I'll do that this week. Probably Tuesday or Wednesday. But having this lib on npm totally makes sense.

**Comment by Tmarty** [comment]
+1

**Comment by rendro** [comment]
Published to npm: https://www.npmjs.com/package/easy-pie-chart

**Comment by mrzmyr** [comment]
:+1:
