### ISSUE TITLE
easy-pie-chart and addthis conflict

### ISSUE THREAD

**Issue by simogeo** [rendro/easy-pie-chart#131]
Hi,

First of all, tanks for the great plugin. It seems there is a conflict when using with addthis social script. Here is the error message I get from firebug : 

> TypeError: this.renderer.draw is not a function
...ate}),this.renderer=new e.renderer(a,e),this.renderer.draw(f),a.dataset&&a.datas...
jquery.....min.js (ligne 9, col. 3038)

Any clue to solve that ?

**Comment by logicboard** [comment]
I am also see this problem.

**Comment by logicboard** [comment]
It is working for me now. It appears AddThis has pushed a fix on their end?

**Comment by rendro** [comment]
Errors with third parties scripts won't be fixed. Probably an error of those scripts. Thanks!

**Comment by simogeo** [comment]
@logicboard : I still experience the problem. I call the following script : http://s7.addthis.com/js/250/addthis_widget.js 

What about you ?

**Comment by simogeo** [comment]
For information, I reported to addThis team. The probably try to fix it !

**Comment by simogeo** [comment]
It seems they fixed it. Thanks to them!
