### ISSUE TITLE
Different charts sizes?

### ISSUE THREAD

**Issue by RichardMisencik** [rendro/easy-pie-chart#139]
Hi, Is it possible to use different chart sizes and colors for different charts based on class or data attribute or whatever?. The idea:

```
$('.chart').easyPieChart({
	size: 80
});

$('.chart.big').easyPieChart({
	size: 100
});
```

**Comment by Romz** [comment]
Subscribe

**Comment by rendro** [comment]
yes but you have to make sure the selectors are mutually exclusive.

In your case the first call

``` javascript
$('.chart').easyPieChart({
    size: 80
});
```

also creates charts for `.chart.big`.

This should work:

``` javascript
$('.chart.small').easyPieChart({
    size: 80
});

$('.chart.big').easyPieChart({
    size: 100
});
```

**Comment by RichardMisencik** [comment]
Oh right that makes sense, thanks
