### ISSUE TITLE
IE 8 only last chart is drawn

### ISSUE THREAD

**Issue by RichardMisencik** [rendro/easy-pie-chart#140]
Hi, in IE 8 there is a bug when using multiple charts only the last one will be drawn. Heres the screenshot:
![demo](https://cloud.githubusercontent.com/assets/2394719/7749359/342c637e-ffcd-11e4-8a1b-89ed7f2753e7.jpg)

Sometimes none of them is drawn, Im also including excanvas and bind polyfill.

**Comment by bigmgreen** [comment]
put excanvas and polyfill in front of css.
