### ISSUE TITLE
Start at another position

### ISSUE THREAD

**Issue by bart** [rendro/easy-pie-chart#165]
Hey everybody,

is it possible to start the graph at the 6 o'clock position instead?

Thanks!

**Comment by bart** [comment]
```
.chart canvas {
    transform: rotate(-180deg);
}
```

Did the trick

**Comment by rendro** [comment]
Or you use the `rotate` option. Then the whole canvas will be rotated. This also works in browsers that do not support css transforms.

**Comment by bart** [comment]
:+1:  Thanks @rendro
