### ISSUE TITLE
How to delete % mark ?

### ISSUE THREAD

**Issue by BumbuKhan** [rendro/easy-pie-chart#174]
How to delete % mark from the end of number inside chart? 
Or how to show another unit, for example Mb

**Comment by janeski-zz** [comment]
Hi,
I am looking for the same thing. Do you have any progress?

**Comment by rendro** [comment]
You can delete it in the css. just remove the pseudo element or change its `content` property.

**Comment by BumbuKhan** [comment]
@rendro thanks

**Comment by janeski-zz** [comment]
Thanks @rendro. To support  multiple units I added new class for each unit: 
`.celsius {
    display: inline-block;
    line-height: 84px;
    z-index: 2;
    font-size: 16px;
  }
  .celsius:after {
    content: "\00b0"; 
    margin-left: 0.1em;
    font-size: .8em;
  }`
