### ISSUE TITLE
  'jquery.easy-pie-chart@latest' is not in the npm registry.

### ISSUE THREAD

**Issue by unixneo** [rendro/easy-pie-chart#207]
CYBER-SA:dark Tim$ npm install jquery.easy-pie-chart --save
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jquery.easy-pie-chart - Not found
npm ERR! 404 
npm ERR! 404  'jquery.easy-pie-chart@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Tim/.npm/_logs/2019-03-24T08_54_03_888Z-debug.log

**Comment by barisdayakseo** [comment]
[Web Site](https://www.barisdayak.com/google-reklam-uzmani-ads-adwords/) page problem.
thanks. help
