### ISSUE TITLE
SVG Renderer

### ISSUE THREAD

**Issue by MichaelCastelbuono** [rendro/easy-pie-chart#78]
I see in the code it says to use either the canvas or SVG renderer. I've been using the canvas render and it works great, but when printing in Chrome or using an html to PDF converter (I'm using raphaeljs) the charts are pixelated. My hope was that the SVG renderer would fix that. Does anyone know if that is in the works?

**Update**
Just saw the branch for https://github.com/rendro/easy-pie-chart/blob/svgrenderer/src/renderer/svg.js. However, I'm getting a few errors. One that must be in a loop because it continues to error.

Here's my chart code.

```
jQuery(function() {
    jQuery('.chart').each(function() {
        createChart(jQuery(this), getChartColor(jQuery(this).data('percent')));
    });
});
var chartOptions = {
    scaleColor: false,
    trackColor: 'rgba(216,209,202,1)',
    lineWidth: 5,
    lineCap: 'butt',
    size: 145,
    rotate: -130,
    renderer: SVGRenderer
};
function createChart($ele, color) {
    chartOptions['barColor'] = color;
    new EasyPieChart($ele.get(0), chartOptions);
}
```

The error is

```
Error: Problem parsing d="M 72.5 2.5 A 70 70 0 0 1 NaN NaN" svg-renderer.js:131
(anonymous function) svg-renderer.js:131
(anonymous function)
```

**btw** the part of the chart that does render now is in SVG format and looks nice and smooth in my pdf. Just need to get it working now.

**Comment by edmondchromatix** [comment]
HI Rendro or MichaelCastelbuono,

Can you please give the working link for the SVG core code?

I found this link is not working 'https://raw2.github.com/rendro/easy-pie-chart/svgrenderer/src/easypiechart.js'.

I got it from the last thread:
'The problem was I was using the core easypiechart.js script from the master branch. Need to use it from the svg branch here'

Thank you so much for your help

Regards,

Ed

**Comment by MichaelCastelbuono** [comment]
Not sure why the link changed, but it should be this file https://github.com/rendro/easy-pie-chart/blob/svgrenderer/src/easypiechart.js -- note, I haven't tested or used this in awhile, but this is the file from the `svgrenderer` branch so it should be the same one I used.
