### ISSUE TITLE
Value percentage into the circle

### ISSUE THREAD

**Issue by mpgn** [rendro/easy-pie-chart#93]
Hi, I have a little problem when I use easy-pie-chart, the value of the circle go outside the circle.
Exemple : 

![ea759e8bacb42e62a2dabf0f56cd4169](https://cloud.githubusercontent.com/assets/5891788/3006195/550fc900-de13-11e3-81e9-2268a0beac04.png)

```
<div class="chart" data-percent="73">73%</div>

<script  src="bower_components/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function(){
            $('.chart').easyPieChart({
                barColor: '#ffffff',
                trackColor: '#222222',
                scaleColor: false,
                size: 300,
                lineWidth: 10,
                lineCap: "square"

            });
        });
</script>
```

Any idea to move the value in the middle ?

**Comment by gentunian** [comment]
This is closed as not being a bug or closed as can't make it dynamic? For every pie chart we need a different width/height?

**Comment by calvinKG** [comment]
HI, 

I am having this problem with the angularJS directive please help

**Comment by pseabury** [comment]
Looking at the Angular version (angular.easypiechart.js), I don't see that the Angular version writes the actual percentage amount (i.e. "73%") on the canvas - is this correct?  I see no parameters in the options object to enable this either.  Is this capability only for the jQuery version?

**Comment by marcotas** [comment]
Hi @rendro it seems the angular version doesn't create the percentage label inside the canvas. Could you help us?
thanks

**Comment by vectrus** [comment]
@rendro Hi there, i have the same issue with the angular version. Are you planning on adding this in the near future?

Please advise, kind regards,
Julius

Never mind :

<div class="wrappereasypie">
        <div easypiechart class="openorderwidget" options="optionsopen" percent="percentopen">
        <div class="easypielabel">
            {{openorderspercentage}}%<br/>
            <span>Open:</span><br/>
            {{openorders.length}}
        </div>

```
    </div>

    <div easypiechart class="openorderwidget" options="optionshandled" percent="percenthandled">
    <div class="easypielabel">
        {{handledorderspercentage}}%<br/>
        <span>Afgehandeld</span><br/>
        {{handledorders.length}}

    </div>
    </div>
</div>
```

.openorderwidget {
    width : 120px;
    position : relative;
    float : left;
}
.easypielabel {
    width : 110px;
    text-align: center;
    position: relative;
    z-index: auto;
    top : 85px;
    float : left;
    display : block;
}

**Comment by chrispruitt** [comment]
Does anyone know if the angular version was ever updated to add the percentage to the middle?
